apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dvffdolb4-python
  janus-idp.io/tekton: dvffdolb4-python
  backstage.io/kubernetes-id: dvffdolb4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dvffdolb4-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
